version: '3.8'

services:
  zitadel:
    restart: always
    image: ghcr.io/zitadel/zitadel:latest
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode external'
    environment:
      - 'ZITADEL_DATABASE_COCKROACH_HOST=crdb'
      - 'ZITADEL_EXTERNALSECURE=true'
      - 'ZITADEL_EXTERNALDOMAIN=${DOMAIN}'
      - 'ZITADEL_EXTERNALPORT=443'
      # - 'ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME=root'
      # - 'ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD=Test1234#'
    depends_on:
      - crdb
    ports:
      - '172.17.0.1:8586:8080'

  crdb:
    restart: always
    image: 'cockroachdb/cockroach:v22.2.2'
    command: 'start-single-node --insecure'
    ports:
      - '172.17.0.1:9090:8080'
      - '172.17.0.1:26257:26257'
    volumes:
      - './data:/cockroach/cockroach-data:rw'
